### ISSUE TITLE
WASAPI (event) VGZ startup music skipped

### ISSUE THREAD

**Issue by Catarax** [kode54/foo_gep#14] opened 2016-10-04 12:24 UTC
Version: 1.204 (+WASAPI event plugin enabled)
When I play a song like Sonic 3 Title Screen VGZ, it'll skip the beggining of the music of 1 or 2 seconds during the output process.

However, if I convert the VGZ music file to FLAC from foobar2000, i'll get the proper beggining of the track when I play it.

Issue only happening with WASAPI (event) plugin/mode.

Source files:
https://mega.nz/#!bRYEXaaL!Xi36JzTAj4aImLspW5eZ050g3tChRoHzbdyOWvkPNP4

**Comment by kode54** [comment] 2016-10-04 23:42
I cannot reproduce your issue, using:

unRAID 6.2 host machine
MSI Z77A-GD65 v2.0
Core i7 3770
GeForce GTX 960 4GB (passthrough to VM)
Intel HD Audio Family (passthrough to VM)

foobar2000 v1.3.10
Peter's WASAPI Output plug-in v3.2.3

Event mode to HD Audio (Headphones)

With this setup, both the VGM and the FLAC start playback almost instantly. I say almost, because a few milliseconds may be going to startup fade or whatever the defaults are. Both sound the same in that regard, though. I even tried forcing my device's default settings to 192/24/stereo to see if odd settings would affect it.

**Comment by Catarax** [comment] 2016-10-05 03:43
Thanks for having a look, I got it fixed by using WASAPI (push) option which really wait to get the data before playing it (instead of EVENT option).

**Comment by kode54** [comment] 2016-10-05 03:49
Which means your hardware or drivers are not really compatible with the event option, for $reasons. Feel free to close this, then.

**Closed** 2016-10-05 11:07 UTC
